# 31-node network configuration
# 5 anchors + 26 unknowns
# Custom: 85x85m area, seed 22

network:
  n_nodes: 31
  n_anchors: 5
  area_size: 85
  random_seed: 22

optimization:
  use_adaptive_lm: true
  use_line_search: false  # Line search slows convergence
  max_iterations: 100
  lm_initial_lambda: 0.001
  gradient_tol: 1.0e-8
  cost_tol: 1.0e-12

measurements:
  measurement_std: 0.01  # 1cm noise

output:
  verbose: true
  plot_results: true